<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE roms [

<!ELEMENT roms ( rom+ ) >
<!ENTITY deg    "&#176;" ><!-- degree sign -->
<!ENTITY micro  "&#181;" ><!-- micro sign -->

<!ELEMENT rom ( romid, table+ ) >
<!ATTLIST rom base CDATA #IMPLIED>

<!ELEMENT romid ( xmlid, internalidaddress, internalidstring, caseid?, ecuid, year, market, make, model, submodel, transmission, flashmethod?, memmodel, filesize, obsolete? ) >

<!ELEMENT xmlid (#PCDATA) >
<!ELEMENT internalidaddress (#PCDATA) >
<!ELEMENT internalidstring (#PCDATA) >
<!ELEMENT caseid (#PCDATA) >
<!ELEMENT ecuid (#PCDATA) >
<!ELEMENT year (#PCDATA) >
<!ELEMENT market (#PCDATA) >
<!ELEMENT make (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT submodel (#PCDATA) >
<!ELEMENT transmission (#PCDATA) >
<!ELEMENT flashmethod (#PCDATA) >
<!ELEMENT memmodel (#PCDATA) >
<!ELEMENT filesize (#PCDATA) >
<!ELEMENT obsolete (#PCDATA) >

<!ELEMENT table ( #PCDATA | scaling | table | description | data | state )* >
<!ATTLIST table
	type NMTOKENS #IMPLIED
	name CDATA #IMPLIED
	category CDATA #IMPLIED
	storagetype CDATA #IMPLIED
	endian (little | big) #IMPLIED
	sizex CDATA #IMPLIED
	sizey CDATA #IMPLIED
	userlevel (1 | 2 | 3 | 4 | 5) #IMPLIED
	logparam CDATA #IMPLIED
	storageaddress CDATA #IMPLIED >

<!ELEMENT scaling EMPTY >
<!ATTLIST scaling
	units CDATA #REQUIRED
	expression CDATA #REQUIRED
	to_byte CDATA #REQUIRED
	format CDATA #REQUIRED
	fineincrement CDATA #REQUIRED
	coarseincrement CDATA #REQUIRED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT data (#PCDATA) >

<!ELEMENT state (#PCDATA) >
<!ATTLIST state
	name CDATA #REQUIRED
	data CDATA #REQUIRED >
]>
<roms>
  <rom>
    <!--
v0.0.1
	- draft of Bosch M1.3

	In this BASE section define all the common table data and axis attributes.
    Leave out the ROM specific addresses.
-->
  <romid>
   <xmlid>BMWM1.3BASE</xmlid>
   <internalidaddress>0000</internalidaddress>
   <internalidstring>0000</internalidstring>
   <ecuid>0000000000</ecuid>
   <year>1987-1991</year>
   <market>EURO</market>
   <make>BMW</make>
   <model>E30</model>
   <submodel>325i</submodel>
   <transmission>MT/AT</transmission>
   <version>BA114 Edition</version>
  </romid>

<!--Config Switches--> 

	<table type="BitwiseSwitch" name="Fuel Type" category="Configurations">
		<bit position ="7" name="Unleaded"/>
		<description>Untick for leaded petrol</description>
	</table>
	
	<table type="BitwiseSwitch" name="Fuel Quality" category="Configurations">
		<bit position ="6" name="Regular"/>
		<description>Untick for super</description>
	</table>

	<table type="BitwiseSwitch" name="O2 Sensor" category="Configurations">
		<bit position ="5" name="No O2 sensor control"/>
		<description>Tick to disable O2 control</description>
	</table>

	<table type="BitwiseSwitch" name="Transmission Type" category="Configurations">
		<bit position ="1" name="Automatic"/>
		<description>Untick for Manual Transmission</description>
	</table>

	<table type="BitwiseSwitch" name="Purge Valve" category="Configurations">
		<bit position ="3" name="No Purge Valve"/>
		<description>Tick to disable purge valve</description>
	</table>
	
	<table type="BitwiseSwitch" name="EML" category="Configurations">
		<bit position ="2" name="No EML"/>
		<description>Untick to enable Engine Management Light</description>
	</table>
	
	<table type="BitwiseSwitch" name="ASC+T" category="Configurations">
		<bit position ="1" name="No ASC+T"/>
		<description>Untick to enable ASC+T</description>
	</table>
	
	<table type="BitwiseSwitch" name="Variant" category="Configurations">
		<bit position ="0" name="Variant"/>
		<description>Untick for Standard - unclear on this function.</description>
	</table>
 
<!--DTCs--> 


<!--Fuel-->
	
	<table type="2D" name="Injector Dead Time" category="Fuel" storagetype="uint8" endian="little" sizex="5" userlevel="1">
		<scaling units="ms" expression="x*0.010000" to_byte="x/0.010000" format="0.000" fineincrement="0.01" coarseincrement="0.1" />
			<table type="X Axis" name="Volts" storagetype="uint8" endian="little">
				<scaling units="V" expression="x*0.068100" to_byte="x/0.068100" format="0.00" fineincrement="0.1" coarseincrement="1" />
			</table>
		<description>Injector Dead Time settings</description>
	</table>
	
	<table type="3D" name="Fuel Scalar - Idle" category="Fuel" storagetype="uint8" endian="little" sizex="3" sizey="6" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part load fuel scalar when vanos is on (advanced). Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="3D" name="Fuel Scalar - Part Throttle" category="Fuel" storagetype="uint8" endian="little" sizex="16" sizey="16" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".01" coarseincrement="0.05" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part load fuel scalar for low loads. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="3D" name="Fuel Scalar - Part Throttle - Low Load" category="Fuel" storagetype="uint8" endian="little" sizex="8" sizey="16" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part load fuel scalar for low loads. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="3D" name="Fuel Scalar - Part Throttle - Low Load 2" category="Fuel" storagetype="uint8" endian="little" sizex="8" sizey="16" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part load fuel scalar for low loads. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="3D" name="Fuel Scalar - Part Throttle - High Load" category="Fuel" storagetype="uint8" endian="little" sizex="6" sizey="16" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part load fuel scalar for high loads. Increase the value to make richer, decrease to make leaner.</description>
	</table>

	<table type="3D" name="Fuel Scalar - Part Throttle - High Load 2" category="Fuel" storagetype="uint8" endian="little" sizex="6" sizey="16" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part load fuel scalar for high loads. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="2D" name="Fuel Scalar - WOT" category="Fuel" storagetype="uint8" endian="little" sizex="16" userlevel="1">
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement="0.01" coarseincrement="0.1" />
			<table type="X Axis" name="Engine Speed" storagetype="uint8" endian="little">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the WOT fuel scalar for WOT. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="2D" name="Fuel Scalar - WOT 2" category="Fuel" storagetype="uint8" endian="little" sizex="16" userlevel="1">
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement="0.01" coarseincrement="0.1" />
			<table type="X Axis" name="Engine Speed" storagetype="uint8" endian="little">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the WOT fuel scalar for WOT. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="3D" name="Fuel - IAT Compensation" category="Fuel" storagetype="uint8" endian="little" sizex="5" sizey="8" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".01" coarseincrement="0.1" />
			<table type="X Axis" name="Intake Air Temp" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="°C" expression="x*0.75-48" to_byte="(x+48)/0.75" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is a modifier to the fuel scalar based on Intake Air Temp - necessary as the AFM measures flow, not mass. Set all values to 1 to disable when converting to MAF</description>
	</table>
	
	<table type="3D" name="Fuel - IAT Compensation 2" category="Fuel" storagetype="uint8" endian="little" sizex="5" sizey="8" userlevel="1" >
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement=".01" coarseincrement="0.1" />
			<table type="X Axis" name="Intake Air Temp" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="°C" expression="x*0.75-48" to_byte="(x+48)/0.75" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is a modifier to the fuel scalar based on Intake Air Temp - necessary as the AFM measures flow, not mass. Set all values to 1 to disable when converting to MAF</description>
	</table>

	<table type="3D" name="Fuel - Acceleration Enrichment" category="Fuel" storagetype="uint8" endian="little" sizex="4" sizey="4" userlevel="1" >
		<scaling units="%" expression="x*0.007813" format="0.00" fineincrement=".01" coarseincrement="0.1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*0.05" to_byte="x/0.05" format="0.00" fineincrement="0.5" coarseincrement="1" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>Fuel additive during fast acceleration.</description>
	</table>
	
	<table type="2D" name="Fuel - Warmup Enrichment - Idle" category="Fuel" storagetype="uint8" endian="little" sizex="6" userlevel="1">
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement="0.01" coarseincrement="0.1" />
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little">
				<scaling units="°C" expression="x*0.75-48" to_byte="(x+48)/0.75" format="#0.00" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This is the fuel enrichment during idle based on Coolant Temperature. Increase the value to make richer, decrease to make leaner.</description>
	</table>
	
	<table type="2D" name="Fuel - Warmup Enrichment - Part Throttle" category="Fuel" storagetype="uint8" endian="little" sizex="6" userlevel="1">
		<scaling units="%" expression="x*0.007813" to_byte="x/0.007813" format="0.000" fineincrement="0.01" coarseincrement="0.1" />
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little">
				<scaling units="°C" expression="x*0.75-48" to_byte="(x+48)/0.75" format="#0.00" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This is the fuel enrichment during part throttle conditions based on Coolant Temperature. Increase the value to make richer, decrease to make leaner.</description>
	</table>

<!--Lambda Regulation-->

	<table type="2D" name="Closed Loop - Maximum Load" category="Lambda Regulation" storagetype="uint8" endian="little" sizex="12" userlevel="1">
		<scaling units="ms" expression="x*0.05" to_byte="x/0.05" format="0.000" fineincrement="0.05" coarseincrement="0.1" />
			<table type="X Axis" name="Engine Speed" storagetype="uint8" endian="little">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="40" coarseincrement="120" />
			</table>
		<description>This is the maximum engine load for closed loop lambda regulation. Above this load fuel trims will be disabled.</description>
	</table>

<!--Timing-->

    <table type="2D" name="Ignition Timing - Idle - MT/AT in P/N" category="Ignition Timing" storagetype="uint8" endian="little" sizex="8" userlevel="1">
		<scaling units="(°) BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Ignition advance at idle.</description>
    </table>
	
	<table type="3D" name="Ignition Timing - Part Throttle" category="Ignition Timing" storagetype="uint8" endian="little" sizex="16" sizey="16" userlevel="1" >
		<scaling units="&deg;BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part throttle ignition timing map when not WOT.</description>
	</table>
	
	
	<table type="3D" name="Ignition Timing - Part Throttle - Low Load" category="Ignition Timing" storagetype="uint8" endian="little" sizex="8" sizey="16" userlevel="1" >
		<scaling units="&deg;BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part throttle ignition timing map when in lower loads but not WOT.</description>
	</table>
	
	<table type="3D" name="Ignition Timing - Part Throttle - Low Load 2" category="Ignition Timing" storagetype="uint8" endian="little" sizex="8" sizey="16" userlevel="1" >
		<scaling units="&deg;BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part throttle ignition timing map when in lower loads but not WOT.</description>
	</table>
	
	<table type="3D" name="Ignition Timing - Part Throttle - High Load" category="Ignition Timing" storagetype="uint8" endian="little" sizex="6" sizey="16" userlevel="1" >
		<scaling units="&deg;BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part throttle ignition timing map when in higher loads but not WOT.</description>
	</table>
	
	<table type="3D" name="Ignition Timing - Part Throttle - High Load 2" category="Ignition Timing" storagetype="uint8" endian="little" sizex="6" sizey="16" userlevel="1" >
		<scaling units="&deg;BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="load" storagetype="uint8" endian="little" logparam="E2" >
				<scaling units="ms" expression="x*.05" to_byte="x/.05" format="0.00" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the part throttle ignition timing map when in higher loads but not WOT.</description>
	</table>

	<table type="2D" name="Ignition Timing - WOT" category="Ignition Timing" storagetype="uint8" endian="little" sizex="16" userlevel="1" >
		<scaling units="&deg;BTDC" expression="(x*.75)-22.5" to_byte="(x+22.5)/.75" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="#" fineincrement="50" coarseincrement="100" />
			</table>
		<description>This is the WOT ignition timing map.</description>
	</table>
	

<!--Idle Speed Target-->
    <table type="2D" name="Idle speed - MT/AT in P/N" category="Idle Speed Target" storagetype="uint8" endian="little" sizex="4" userlevel="1">
		<scaling units="RPM" expression="x*10" to_byte="x/10" format="0" fineincrement="10" coarseincrement="100"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>Engine idle speed with no additional load.</description>
    </table>
	
    <table type="2D" name="Idle speed - AT in D/R" category="Idle Speed Target" storagetype="uint8" endian="little" sizex="4" userlevel="1">
		<scaling units="RPM" expression="x*10" to_byte="x/10" format="0" fineincrement="10" coarseincrement="100"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>Engine idle speed with no additional load.</description>
    </table>
	
    <table type="2D" name="Idle Speed - AT in D/R - AC On" category="Idle Speed Target" storagetype="uint8" endian="little" sizex="4" userlevel="1">
		<scaling units="RPM" expression="x*10" to_byte="x/10" format="0" fineincrement="10" coarseincrement="100"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>Engine idle speed with AC on.</description>
    </table>
	

<!--Deceleration-->
    <table type="2D" name="Fuel Restore - RPM (AC On)" category="Deceleration" storagetype="uint8" endian="little" sizex="4" userlevel="1">
		<scaling units="RPM" expression="x*40" to_byte="x/40" format="0" fineincrement="40" coarseincrement="400"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>Below this Engine Speed, fuel injectors are always turned on. To disable fuel cut during deceleration with the Throttle closed, increase this table as high as you want.</description>
    </table>
	
    <table type="2D" name="Fuel Restore - RPM" category="Deceleration" storagetype="uint8" endian="little" sizex="4" userlevel="1">
		<scaling units="RPM" expression="x*40" to_byte="x/40" format="0" fineincrement="40" coarseincrement="400"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>Below this Engine Speed, fuel injectors are always turned on. To disable fuel cut during deceleration with the Throttle closed, increase this table as high as you want.</description>
    </table>

<!--Limiters-->
	<table type="2D" name="Rev Limiter" category="Limiters" storagetype="uint8" endian="little" sizey="1" userlevel="1">
		<scaling units="RPM" expression="912500/x" format="0" fineincrement="40" coarseincrement="400" />
			<table type="Static Y Axis" name="RPM" sizey="1">
				<data>RPM Limit</data>
			</table>
		<description>Rev Limiter</description>
	</table>
	
	<table type="2D" name="VSS Limiter" category="Limiters" storagetype="uint8" endian="little" sizey="1" userlevel="1">
		<scaling units="RPM" expression="912500/x" format="0" fineincrement="40" coarseincrement="400" />
			<table type="Static Y Axis" name="RPM" sizey="1">
				<data>RPM Limit</data>
			</table>
		<description>Rev Limiter when Vehicle Speed Sensor is missing.</description>
	</table>

<!--Sensor Scaling-->

	
	<table type="2D" name="AFM Transfer - Magnitude" category="Sensors Scaling" storagetype="uint8" endian="little" sizex="8"  userlevel="2" >
	   <scaling units="-" expression="x" to_byte="x"  format="0.00" fineincrement=".01" coarseincrement=".1" />
			<table type="Static X Axis" name="Decimal" sizex="8">
				<data>1</data>
				<data>2</data>
				<data>3</data>
				<data>4</data>
				<data>5</data>
				<data>6</data>
				<data>7</data>
				<data>8</data>
			</table>
		<description>This table is used in conjunction with AFM Transfer - Exponent and AFM Functiong - Curve to generate a 256 byte AFM transfer function.
		Flow m^3/hr = "AFM Transfer - Magnitude" * (2^"AFM Transfer - Exponent") * "AFM Transfer - Curve"</description>
	</table>
	
	<table type="2D" name="AFM Transfer - Exponent" category="Sensors Scaling" storagetype="int8" endian="little" sizex="8"  userlevel="2" >
	   <scaling units="-" expression="x" to_byte="x"  format="0.00" fineincrement=".01" coarseincrement=".1" />
			<table type="Static X Axis" name="Decimal" sizex="8">
				<data>1</data>
				<data>2</data>
				<data>3</data>
				<data>4</data>
				<data>5</data>
				<data>6</data>
				<data>7</data>
				<data>8</data>
			</table>
		<description>This table is used in conjunction with AFM Transfer - Exponent and AFM Functiong - Curve to generate a 256 byte AFM transfer function.
		Flow m^3/hr = "AFM Transfer - Magnitude" * (2^"AFM Transfer - Exponent") * "AFM Transfer - Curve"</description>
	</table>

	<table type="2D" name="AFM Transfer - Curve" category="Sensors Scaling" storagetype="uint8" endian="little" sizex="32"  userlevel="2" >
	   <scaling units="-" expression="x" to_byte="x"  format="0.00" fineincrement=".01" coarseincrement=".1" />
			<table type="Static X Axis" name="Decimal" sizex="32">
				<data>0.00</data>
				<data>0.02</data>
				<data>0.04</data>
				<data>0.06</data>
				<data>0.08</data>
				<data>0.10</data>
				<data>0.12</data>
				<data>0.14</data>
				<data>0.16</data>
				<data>0.18</data>
				<data>0.20</data>
				<data>0.22</data>
				<data>0.24</data>
				<data>0.26</data>
				<data>0.28</data>
				<data>0.30</data>
				<data>0.00</data>
				<data>0.32</data>
				<data>0.64</data>
				<data>0.96</data>
				<data>1.26</data>
				<data>1.58</data>
				<data>1.90</data>
				<data>2.20</data>
				<data>2.52</data>
				<data>2.82</data>
				<data>3.14</data>
				<data>3.46</data>
				<data>3.78</data>
				<data>4.08</data>
				<data>4.40</data>
				<data>4.70</data>
			</table>
		<description>This table is used in conjunction with AFM Transfer - Exponent and AFM Functiong - Curve to generate a 256 byte AFM transfer function.
		Flow m^3/hr = "AFM Transfer - Magnitude" * (2^"AFM Transfer - Exponent") * "AFM Transfer - Curve"</description>
	</table>
	
	<table type="2D" name="ECT Sensor Scaling" category="Sensors Scaling" storagetype="uint8" endian="little" sizex="12" userlevel="1">
		<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.00" fineincrement="2" coarseincrement="10"/>
			<table type="Y Axis" name="Voltage" storagetype="uint8" endian="little">
				<scaling units="Volts" expression="x*0.019608" to_byte="x/0.019608" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			</table>
		<description>This is the scaling for the Engine Coolant Temperature sensor.</description>
    </table>

	
<!--Outputs-->
         
	<table type="3D" name="Canister Purge PWM (Without CAT)" category="Outputs" storagetype="uint8" endian="little" sizex="8" sizey="8" userlevel="1" >
		<scaling units="%" expression="x*(100/255)" to_byte="x/(100/255)" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2">
				<scaling units="ms" expression="x*0.05" to_byte="x/0.05" format="0.00" fineincrement="0.05" coarseincrement="0.1" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="0" fineincrement="40" coarseincrement="120" />
			</table>
		<description>Cannister Purge PWM control for models not equipped with a Catalytic Converter. Can be re-purposed to control other PWM controlled device e.g. boost solenoid.</description>
	</table>
  
	<table type="3D" name="Canister Purge PWM (With CAT)" category="Outputs" storagetype="uint8" endian="little" sizex="8" sizey="8" userlevel="1" >
		<scaling units="%" expression="x*(100/255)" to_byte="x/(100/255)" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="X Axis" name="Load" storagetype="uint8" endian="little" logparam="E2">
				<scaling units="ms" expression="x*0.05" to_byte="x/0.05" format="0.00" fineincrement="0.05" coarseincrement="0.1" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="little" logparam="P8">
				<scaling units="RPM" expression="x*40" to_byte="x/40" format="0" fineincrement="40" coarseincrement="120" />
			</table>
		<description>Cannister Purge PWM control for models equipped with a Catalytic Converter. Can be re-purposed to control other PWM controlled device e.g. boost solenoid.</description>
	</table>



</rom>
 

  <rom base="BMWM1.3BASE">
    <!-- In this ROM specific section define only the attributes missing or that need
     to be changed compared to the common table data and axis attributes in the BASE.